config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  root to: 'works#index'
  resources :contacts, only: [:new, :create]
  resources :blogs, except: :index
  resources :works do
    collection do
      get 'works' 
    end
    member do
      get 'zoom'
    end
    member do
      get 'creater'
    end
    member do
      get 'types'
    end
    member do
      get 'creater_type'
    end
    collection do
      get 'profile'
    end
    collection do
      get 'contact'
    end
    collection do
      get 'link'
    end
    collection do
      get 'list'
    end
    collection do
      get 'show_mail'
    end
  end
end

app/views/shared/_contents-body.html.erb
<% if @kinari %>
  <% @works.each do |work| %>
      <div class="content">
        <div>
          <% work.images.each_with_index do |image,index| %>
            <% if index == 0 %>
              <%= link_to image_tag(image,class:"content-image") ,work_path(work.id , creater: @creater_id, :serch => @artist_search)%>
            <% end %>
          <% end %>
        </div>
        <div class="content-title">
          <span class="title-work"><%= link_to work.title , work_path(work.id, creater: @creater_id, :serch => @artist_search)%></span><span class="date-work"><%= link_to work.created_year ,work_path(work.id) %></span>
        </div>
      </div>
  <% end %>
<% else %>
  <% @works.each do |work| %>
      <div class="content">
        <div>
          <% work.images.each_with_index do |image,index| %>
            <% if index == 0 %>
              <%= link_to image_tag(image,class:"content-image") ,work_path(work.id, creater: @creater_id, :serch => @artist_search)%>
            <% end %>
          <% end %>
        </div>
        <div class="content-title">
          <span class="title-work"><%= link_to work.title , work_path(work.id, creater: @creater_id, :serch => @artist_search)%></span><span class="date-work"><%= link_to work.created_year ,work_path(work.id, :serch => @artist_search) %></span>
        </div>
      </div>
  <% end %>
<% end %>

app/views/shared/_creater-type-menu.html.erb
<ul id="creater-type-list" style="display: none;">
  <%= link_to(types_work_path(id: 0) , remote: true) do %>
    <li id="artist-name">
      全ての作品
    </li>
  <% end %>
<% @type.each do |type| %>
  <% unless type.id == 0 %>
    <%= link_to(types_work_path(type.id), remote: true) do %>
      <li id="artist-name">
        <%= type.name  %>
      </li>
    <% end %>
  <% end %>
<% end %>
</ul>

app/views/shared/_creater.html.erb
<% @creaters.each do |work| %>
 <div class="content">
  <div>
    <%= link_to image_tag("http://drive.google.com/uc?export=view&id=#{work.image}",class:"content-image") ,work_path(work.id)%>
  </div>
  <div class="content-title">
    <span class="title-work"><%= link_to work.title , work_path(work.id)%></span><span class="date-work"><%= link_to work.created_year ,work_path(work.id) %></span>
  </div>
 </div>
<% end %>

app/views/shared/_each-menu.html.erb
作者別
カテゴリー別
制作年別

<ul>
<% @creaters.each do |creater| %>
  <% if creater.id != 0 %>
    <li>
      <%= link_to reater.name,  creater_work_path(creater.id)%>
    </li>
  <% end %>
<% end %>
</ul>

app/views/shared/_form-menu.html.erb
<div class="menu-btns">
  <%= link_to(new_work_path) do%>
    <div class="menu-btn">
      作品新規登録
    </div>
  <% end %>
  <%= link_to(list_works_path) do%>
    <div class="menu-btn">
      作品情報一覧/編集
    </div>
  <%end%>
  <%= link_to(new_blog_path) do%>
    <div class="menu-btn">
      ブログの投稿
    </div>
  <%end%>
  <%= link_to(show_mail_works_path) do%>
    <div class="menu-btn">
      問い合わせ一覧
    </div>
  <%end%>
</div>

app/views/shared/_frist-header.html copy.erb
<div id="contact-message">
  <%= render 'contacts/success'%>
</div>
<div id="contactbox">
  <%= render 'contacts/contact_form' %>
</div>
<header class='frist-header'>
<%= link_to image_tag('komadorihouse_kana.png',id:"rogo-kana-pc" ),'/' %>
  <div class="title-info">
    <%= link_to image_tag('komadorihouse_kana.png',id:"rogo-kana" ),'/' %>
    <%= link_to image_tag('old_rogo_Black_close.png',id:"rogo-close" ),'/' %>
    <div class="info">
      <div class="info-text">
          <%= @info %>
      </div>
    </div>
  </div>
  <div id="menuopen-btn">
    <div id="openbtn-top" class="openbtn">
    </div>
    <div id="openbtn-center" class="openbtn cb">
    </div>
    <div id="openbtn-bottom" class="openbtn cb">
    </div>
  </div>
    <div id="menu">
    <ul>
      <li class="menu-font" id="news-btn"><%= link_to "News",root_path %></li>
      <li class="menu-font" id="works-btn"><%= link_to "Works",works_works_path %></li>
      <li class="menu-font" id="profile-btn"><%= link_to "Profile",profile_works_path %></li>
      <li class="menu-font" id="contact-btn">Contact</li>
      <li class="menu-font" id="link-btn"><%= link_to "Link" ,link_works_path %></li>
    </ul>
  </div>
  <div id="mobile-menu-area">
    <div id="mobile-menu" style="display: none;">
      <ul>
        <%= link_to(root_path) do %>
          <li class="menu-font">News</li>
        <% end %>
          <li><div class="mobilemenu-border"></div></li>
        <%= link_to(works_works_path) do %>  
          <li class="menu-font">Works</li>
        <% end %>
          <li><div class="mobilemenu-border"></div></li>
        <%= link_to(profile_works_path) do %>  
          <li class="menu-font">Profile</li>
        <% end %>
          <li><div class="mobilemenu-border"></div></li>
          <li class="menu-font" id="contact-btnm">Contact</li>
          <li><div class="mobilemenu-border"></div></li>
        <%= link_to(link_works_path) do %>
          <li class="menu-font">Link</li>
        <% end %>
      </ul>
    </div>
  </div>
    <% if current_page?(action: 'index', controller:'works') %>
      <%= image_tag("news.png",id:"nomal",class:"image-area-rogo") %>
    <% elsif current_page?(action: 'works', controller:'works') %>
      <%= image_tag("works.png",id:"nomal",class:"image-area-rogo") %>
    <% elsif current_page?(action: 'profile', controller:'works') %>
      <%= image_tag("profile.png",id:"nomal",class:"image-area-rogo") %>
    <% elsif current_page?(action: 'link', controller:'works') %>
      <%= image_tag("link.png",id:"nomal",class:"image-area-rogo") %>
    <% end %>
      <%= image_tag("works.png",id:"works",class:"image-area-rogo",style:"display: none;") %>
      <%= image_tag("profile.png",id:"profile",class:"image-area-rogo",style:"display: none;") %>
      <%= image_tag("contact.png",id:"contact",class:"image-area-rogo",style:"display: none;") %>
      <%= image_tag("link.png",id:"link",class:"image-area-rogo",style:"display: none;") %>
      <%= image_tag("news.png",id:"news",class:"image-area-rogo",style:"display: none;") %>
</header>

app/views/shared/_frist-header.html.erb
<div id="contact-message">
  <%= render 'contacts/success'%>
</div>
<div id="contactbox">
  <%= render 'contacts/contact_form' %>
</div>
<header class='frist-header'>

  <div id="menuopen-btn">
    <div id="openbtn-top" class="openbtn">
    </div>
    <div id="openbtn-center" class="openbtn cb">
    </div>
    <div id="openbtn-bottom" class="openbtn cb">
    </div>
  </div>
    <div id="menu">
    <ul>
      <li class="menu-font" id="news-btn"><%= link_to "News",root_path %></li>
      <li class="menu-font" id="works-btn"><%= link_to "Works",works_works_path %></li>
      <li class="menu-font" id="profile-btn"><%= link_to "Profile",profile_works_path %></li>
      <li class="menu-font" id="contact-btn">Contact</li>
      <li class="menu-font" id="link-btn"><%= link_to "Link" ,link_works_path %></li>
    </ul>
  </div>
  <div id="mobile-menu-area">
    <div id="mobile-menu" style="display: none;">
      <ul>
        <%= link_to(root_path) do %>
          <li class="menu-font">News</li>
        <% end %>
          <li><div class="mobilemenu-border"></div></li>
        <%= link_to(works_works_path) do %>  
          <li class="menu-font">Works</li>
        <% end %>
          <li><div class="mobilemenu-border"></div></li>
        <%= link_to(profile_works_path) do %>  
          <li class="menu-font">Profile</li>
        <% end %>
          <li><div class="mobilemenu-border"></div></li>
          <li class="menu-font" id="contact-btnm">Contact</li>
          <li><div class="mobilemenu-border"></div></li>
        <%= link_to(link_works_path) do %>
          <li class="menu-font">Link</li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to image_tag('komadorihouse_kana.png',id:"rogo-kana-pc" ),'/' %>
  <div class="title-info">
    <%= link_to image_tag('komadorihouse_kana.png',id:"rogo-kana" ),'/' %>
    <%= link_to image_tag('old_rogo_Black_close.png',id:"rogo-close" ),'/' %>
  <div class="info">
      <div class="info-text">
          <%= @info %>
      </div>
    </div>
  </div>
    <%= link_to(profile_works_path) do %>
      <% if current_page?(action: 'index', controller:'works') %>
        <%= image_tag("news.png",id:"nomal",class:"image-area-rogo") %>
      <% elsif current_page?(action: 'works', controller:'works') %>
        <%= image_tag("works.png",id:"nomal",class:"image-area-rogo") %>
      <% elsif current_page?(action: 'profile', controller:'works') %>
        <%= image_tag("profile.png",id:"nomal",class:"image-area-rogo") %>
      <% elsif current_page?(action: 'link', controller:'works') %>
        <%= image_tag("link.png",id:"nomal",class:"image-area-rogo") %>
      <% else %>
        <%= image_tag("works.png",id:"nomal",class:"image-area-rogo") %>
      <% end %>
        <%= image_tag("works.png",id:"works",class:"image-area-rogo",style:"display: none;") %>
        <%= image_tag("profile.png",id:"profile",class:"image-area-rogo",style:"display: none;") %>
        <%= image_tag("contact.png",id:"contact",class:"image-area-rogo",style:"display: none;") %>
        <%= image_tag("link.png",id:"link",class:"image-area-rogo",style:"display: none;") %>
        <%= image_tag("news.png",id:"news",class:"image-area-rogo",style:"display: none;") %>
        <%= image_tag("nomal.png",id:"nomalrogo",class:"image-area-rogo",style:"display: none;") %>
    <% end %>
</header>

app/views/shared/_index.html.erb
<% @workslist.each do |work| %>
        <li class="contents-list">
          <span class="title-work">
          <%= link_to work.title ,work_path(work.id) %>
          </span>
          <span class="date-work">
          <%= link_to work.created_year ,work_path(work.id) %>
          </span>
        </li>
      <% end %>

app/views/shared/_master-menu.html.erb
<ul id="artists-list" style="display: none;">
  <%= link_to(works_works_path , remote: true) do %>
    <li id="artist-name" class="artist-name">
      全てのアーティスト
    </li>
  <% end %>
<% @creaters.each do |creater| %>
  <% unless creater.id == 0 || creater.id == 4 || creater.id == 5  %>
    <%= link_to(creater_work_path(creater.id), remote: true) do %>
      <li id="artist-name" class="artist-name <%= "a#{creater.id}" %>">
        <%= creater.name  %>
        <%#comitt用削除可%>
      </li>
    <% end %>
  <% end %>
<% end %>
</ul>

app/views/shared/_more.html.erb
<%= paginate @workslist ,:param_name => 'index',remote: true %>

app/views/shared/_news_index.html.erb
<ul id="contents-lists">
  <% @blogslist.each do |list| %>    
    <li class="contents-list">
      <div class="news-title-index">
        <%= link_to list.title ,blog_path(list.id) %>
      </div>
      <div class="news-date-index">
        <%= link_to list.created_at.to_s(:date_jp) ,blog_path(list.id) %>
      </div>
    </li>
  <% end %>
</ul>

app/views/shared/_type-menu.html.erb
<ul id="type-list" style="display: none;">
  <%= link_to(types_work_path(id: 0) , remote: true) do %>
    <li id="artist-name">
      全ての作品
    </li>
  <% end %>
<% @type.each do |type| %>
  <% unless type.id == 0 %>
    <%= link_to(types_work_path(type.id), remote: true) do %>
      <li id="artist-name">
        <%= type.name  %>
      </li>
    <% end %>
  <% end %>
<% end %>
</ul>

app/views/shared/_works_index.html.erb
<div class="index">
    <div class="index-title">
      Works Index
    </div>
    <div class="index-contents">
      <ul id="contents-lists">
       <%= render 'shared/index' ,:param_name => "index"%>
      </ul>
      <div id="more-lists">
      </div>
    </div>
     <span id="next">
        <%= link_to_next_page @workslist, 'もっと見る',id:"more-index" ,:param_name => "index" ,remote: true %>
     </span>
</div>

app/views/shared/_workslist.html.erb
<ul class="contents-lists">
      <% @workslist.each do |work| %>
        <li class="contents-list">
          <span class="title-work">
          <%= link_to work.title ,work_path(work.id) %>
          </span>
          <span class="date-work">
          <%= link_to work.created_year ,work_path(work.id) %>
          </span>
        </li>
      <% end %>
</ul>